### ISSUE TITLE
Too Many Redirects

### ISSUE THREAD

**Issue by MJGD** [gocd-contrib/google-oauth-authorization-plugin#4]
I recently upgraded GoCD and switched to using this plugin. 

We are frequently seeing:

![image](https://user-images.githubusercontent.com/30752102/35511579-5745fe04-04f4-11e8-93f2-5ff44b8400b7.png)

When loading the admin interface and in the logs we get:

go-server.log:
```
2018-01-29 10:48:53,662 ERROR [qtp662822946-24] BasicAuthenticationFilter:64 - java.lang.RuntimeException: Interaction with plugin with id 'cd.go.authorization.google' implementing 'authorization' extension failed while requesting for 'go.cd.authorization.authenticate-user'. Reason: [java.lang.RuntimeException: Api call to `/oauth2/v1/userinfo` failed with error: `{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
```

plugin-cd.go.authorization.google.log:
```
2018-01-29 10:48:53,645 ERROR [qtp662822946-24] GooglePlugin:82 - Error while executing request go.cd.authorization.authenticate-user
java.lang.RuntimeException: Api call to `/oauth2/v1/userinfo` failed with error: `{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
`
        at cd.go.authorization.google.GoogleApiClient.executeRequest(GoogleApiClient.java:130)
        at cd.go.authorization.google.GoogleApiClient.userProfile(GoogleApiClient.java:117)
        at cd.go.authorization.google.executors.UserAuthenticationRequestExecutor.execute(UserAuthenticationRequestExecutor.java:52)
        at cd.go.authorization.google.requests.Request.execute(Request.java:47)
        at cd.go.authorization.google.GooglePlugin.handle(GooglePlugin.java:65)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:316)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
        at com.thoughtworks.go.plugin.access.authorization.AuthorizationExtension.authenticateUser(AuthorizationExtension.java:223)
        at com.thoughtworks.go.server.security.providers.PreAuthenticatedAuthenticationProvider.authenticateUser(PreAuthenticatedAuthenticationProvider.java:102)
        at com.thoughtworks.go.server.security.providers.PreAuthenticatedAuthenticationProvider.doAuthenticate(PreAuthenticatedAuthenticationProvider.java:77)
        at com.thoughtworks.go.server.security.providers.PreAuthenticatedAuthenticationProvider.authenticate(PreAuthenticatedAuthenticationProvider.java:71)
        at org.springframework.security.providers.ProviderManager.doAuthentication(ProviderManager.java:195)
        at org.springframework.security.AbstractAuthenticationManager.authenticate(AbstractAuthenticationManager.java:46)
        at org.springframework.security.intercept.AbstractSecurityInterceptor.authenticateIfRequired(AbstractSecurityInterceptor.java:319)
        at org.springframework.security.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:258)
        at org.springframework.security.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:106)
        at org.springframework.security.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.ui.SessionFixationProtectionFilter.doFilterHttp(SessionFixationProtectionFilter.java:67)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.DenyGoCDAccessForArtifactsFilter.doFilterHttp(DenyGoCDAccessForArtifactsFilter.java:44)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.ui.ExceptionTranslationFilter.doFilterHttp(ExceptionTranslationFilter.java:101)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.providers.anonymous.AnonymousProcessingFilter.doFilterHttp(AnonymousProcessingFilter.java:105)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.UserEnabledCheckFilter.doFilterHttp(UserEnabledCheckFilter.java:64)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.ReAuthenticationFilter.doFilterHttp(ReAuthenticationFilter.java:61)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:271)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.ui.basicauth.BasicProcessingFilter.doFilterHttp(BasicProcessingFilter.java:173)
        at com.thoughtworks.go.server.security.BasicAuthenticationFilter.doFilterHttp(BasicAuthenticationFilter.java:62)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:271)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.WebBasedAuthenticationFilter.doFilterHttp(WebBasedAuthenticationFilter.java:61)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.OauthAuthenticationFilter.doFilterHttp(OauthAuthenticationFilter.java:61)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.RemoveAdminPermissionFilter.doFilterHttp(RemoveAdminPermissionFilter.java:89)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.DisallowExternalReAuthenticationFilter.doFilterHttp(DisallowExternalReAuthenticationFilter.java:44)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.ui.logout.LogoutFilter.doFilterHttp(LogoutFilter.java:89)
        at com.thoughtworks.go.server.security.GoLogoutFilter.doFilterHttp(GoLogoutFilter.java:48)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilterHttp(HttpSessionContextIntegrationFilter.java:235)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.web.i18n.LocaleResolver.doFilter(LocaleResolver.java:41)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.ModeAwareFilter.doFilter(ModeAwareFilter.java:49)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:174)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at com.thoughtworks.go.server.web.BackupFilter.doFilter(BackupFilter.java:86)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at com.thoughtworks.go.server.web.DefaultHeadersFilter.doFilter(DefaultHeadersFilter.java:34)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
```

It seems to occur after a little while afk so is possibly related to creds expiring.

Clearing the cookies works as suggested, but does anyone know how to reconfigure this so we don't need to?

Please let me know if you need any more information.

**Comment by BrendanBall** [comment]
We're also experiencing this problem. The only way I can get it to work again is to delete all my cookies (I don't know which google cookie it uses) which means I have to login to all my websites again. Deleting just gocd cookies doesn't fix the problem. Hopefully we can make this high priority as it basically makes this plugin unusable.

**Comment by MJGD** [comment]
@BrendanBall there's only one gocd cookie created.

Deleting that one has the desired effect, so there is a good workaround.

In Chrome going to "Settings -> Advanced -> Content Settings -> Cookies -> See all cookies and site data" and then searching for gocd should return one cookie, deleting that should reset your auth issue. Other browsers should have similar functionality.

**Comment by agalpin** [comment]
We are also having the same issue, we were having to restart the server every day, it appears to be expiring tokens from what i can see. Switching back to the other plugin appears to work for us. Was a pain trying to explain to 60 people how to delete their cookies!

**Comment by bdpiparva** [comment]
The redirection issue is in GoCD when session is having invalid access token for a user. The [PR#4274](https://github.com/gocd/gocd/pull/4274) is open to fix this issue.

**Comment by BrendanBall** [comment]
@MJGD should the gocd cookie not be in the site specific cookies? ie. you can delete it under Developer tools -> Application -> clear site data? Because that didn't make it work again.

**Comment by bdpiparva** [comment]
@BrendanBall --- Basic auth is uses different authentication flow. Basic auth is already having [safety check](https://github.com/gocd/gocd/blob/9f5da26a5c6c8b294f26fdec8b618a8f2edb47ce/server/src/main/java/com/thoughtworks/go/server/security/providers/PluginAuthenticationProvider.java#L79-L80) to prevent infinite redirection. We have added same safety check in [PR#4247](https://github.com/gocd/gocd/pull/4274) for web based authentication plugin.

**Comment by BrendanBall** [comment]
ok cool, hopefully they'll release a patch  soon seen as it's already merged. thanks

**Comment by MJGD** [comment]
@bdpiparva thanks for fixing this :-)

**Comment by bdpiparva** [comment]
Experimental build for this fix is available on [https://www.gocd.org/download](https://www.gocd.org/download) under **experimental** section.

**Comment by michaelbannister** [comment]
Note - 18.2 is now released, which fixes this.

**Comment by bdpiparva** [comment]
Closing the issue as it is fixed in [GoCD release 18.2.0](https://www.gocd.org/download/#osx).

**Comment by blzysh** [comment]
I'm seeing this again in: gocd-server:v18.6.0

Anyone else?

**Comment by arvindsv** [comment]
@blzysh There was a similar (not same) issue reported earlier today (https://github.com/gocd/gocd/issues/4853). That one is with normal password auth, but will be investigated soon. Will add this too.

Please provide any extra information that you think might be relevant.

/cc @bdpiparva

**Comment by blzysh** [comment]
Thanks @arvindsv - I'll try to get you some actual log data this weekend. I was able to roll back to version 18.5.0 and I do not get the redirect/cookie issue but it does just totally log me out, after that I can sign back in again without clearing my cookies. This is easier for my users to deal with right now vs. cleaning out their cookies.
